### ISSUE TITLE
Handle failures from Ups Freight API

### ISSUE THREAD

**Issue by dividedharmony** [friendlycart/friendly_shipping#102]
In `lib/friendly_shipping/services/ups_freight.rb`:
```rb
def rate_estimates(shipment, options:, debug: false)
  freight_rate_request_hash = GenerateFreightRateRequestHash.call(shipment: shipment, options: options)
  request = build_request(:rates, freight_rate_request_hash, debug)

  client.post(request).fmap do |response|
    ParseFreightRateResponse.call(response: response, request: request)
  end
end
```
This works when the `client.post` is successful, but if the API returns a failure (such as a 500 error), then I think this method should return something other than a failure monad with the raw API response.

**Comment by mamhoff** [comment]
Hm, I think I disagree. The design decision here was to return a Failure Monad (indicating failure) that can be serialized to a string ("500 Internal Server Error", ah well, not the best string, but at least it doesn't type error), and additional information to help debug (the raw response). I think handling failure here is responsibility of the app requiring the library. :)
