### ISSUE TITLE
Use the Ups Freight RESTful API

### ISSUE THREAD

**Issue by dividedharmony** [friendlycart/friendly_shipping#103]
In `lib/friendly_shipping/services/ups_freight.rb`, we have:
```rb
RESOURCES = {
  rates: '/ship/v1801/freight/rating/ground',
  labels: '/ship/v1607/freight/shipments/Ground'
}.freeze
```
but I believe the newer API endpoint for rates is `/rest/FreightRate`. We have come across at least one case where the old API endpoint (the one used in FriendlyShipping) returns a 500 error where the new endpoint returns a successful response.

**Comment by mamhoff** [comment]
Weirdly, UPS' newer documentation uses the endpoints listed above. In order to change the endpoint, one could conceivably subclass the service class and overwrite the `RESOURCES` constant in order to use the same API with a different endpoint.

**Comment by pelargir** [comment]
I mis-spoke during standup this morning. I think the REST endpoints above are actually old, and the endpoints we're currently using are the newer ones. I can find the endpoints above in older documentation (2019 and prior) but the latest docs from 2020 have no reference to the above endpoints, only to the endpoints we're currently using in the app.

I'm trying to confirm directly w/UPS Freight API support personnel that the endpoint we're currently using is correct. I'm also asking for an explanation as to why the older docs have a different endpoint.

**Comment by pelargir** [comment]
I think we should add support to Friendly Shipping for both endpoints, unless we get official word from UPS that one or the other is no longer being actively developed. Each endpoint has significant enough differences to warrant separate classes to generate requests.

**Comment by pelargir** [comment]
Closing this since UPS Freight is now TForce, and they are implementing [a new API](https://developer.tforcefreight.com/) separate from UPS.
